WIP: Require Node.js 6, add TypeScript definition
sindresorhus/p-any pull request #4
Opened 2019-03-08 02:02 UTC by BendingBender

Waiting for:
- https://github.com/sindresorhus/p-cancelable/pull/16
- https://github.com/sindresorhus/p-some/pull/9

2019-03-13 11:02 UTC, sindresorhus requested changes

2019-03-13 11:02 UTC, sindresorhus commented on index.d.ts
> + *
See https://github.com/sindresorhus/meow/pull/116#discussion_r265038725

2019-03-13 11:02 UTC, sindresorhus commented on index.d.ts
> +export default function pAny<T>(
Any better name than `T`?

2019-03-13 11:02 UTC, sindresorhus commented on index.d.ts
> +>;
Could you depend on https://github.com/sindresorhus/type-fest and use https://github.com/sindresorhus/type-fest/blob/aea4f4d646259445b55e08a76c15b831c476dc34/index.d.ts#L65 ?

2019-03-13 11:02 UTC, sindresorhus commented on index.d.ts
> +>;
Unrelated, but while I got you here. Any feedback on the naming in my version versus yours. `RecordType, KeyType` vs `ObjectType, KeysType`.

2019-03-13 11:02 UTC, sindresorhus commented on index.js
> +	return new PCancelable((resolve, reject, onCancel) => {
I wonder if we could use `PCancelable.fn()` here instead of the constructor.

2019-03-13 11:02 UTC, sindresorhus commented on test.js
> +	const f = [Promise.resolve(1)];
```suggestion
	const fixture = [Promise.resolve(1)];
```

2019-03-13 11:47 UTC, BendingBender commented on index.d.ts
> +>;
I think `ObjectType` and `KeysType` are clearer.

2019-03-13 19:51 UTC, sindresorhus commented
Can you mention in the readme that the returned promise is cancelable (and link to `p-cancelable`)? I think we forgot to do this with `p-some` too.

2019-03-14 17:52 UTC, sindresorhus approved these changes

2019-03-14 17:53 UTC, merged

2019-03-14 17:54 UTC, sindresorhus commented
@BendingBender Just wanted to say how incredible thankful I am for all your help with adding TS definitions and your high-quality work. 🙌👍🙏

2019-03-14 21:05 UTC, BendingBender commented
You're welcome. Thank you for your great modules!